#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PostToolUse hook (Edit|Write): nudge when a rule-bearing doc changes.

Ported from the sibling project (ferrislicer) 2026-08-26, adapted only in
RULE_BEARING: this project has no docs/INVARIANTS.md (its enforcement ledger
is docs/invariant-register.md, GENERATED by packages/invariants — a nudge
here is a "did you mean to hand-edit a generated file" signal as much as a
register one) and no docs/refactors/ directory, so that path is dropped
rather than invented.

Non-blocking, in-conversation layer of the governance chain. If the edited
file is a rule-bearing path and the register (docs/RULES-GROUPED.md) has no
pending working-tree change, remind the session of the same-commit register
rule stated in docs/RULES-GROUPED.md's own "Maintaining this file (the
contract)" section. This hook itself never blocks (advisory print only).

Corrected 2026-09-01: at port time (see
docs/superpowers/2026-08-26-register-check-port.md) this project genuinely
had no pre-commit hook, so this docstring said so. `.githooks/pre-commit`
was added a few minutes later the same day and does gate commits — it runs
`scripts/register_check.py --fast` on any commit touching a governance file,
once a clone has run `pnpm hooks:install` (sets `core.hooksPath`). What this
project still lacks is CI: no `.github/workflows` exists, so a clone that
never installed the hook, or a commit that touches none of the governance
paths, is ungated. This hook's own advisory nudge stays useful either way —
it fires in-conversation, before staging, regardless of whether the
pre-commit gate is installed.
"""
import json
import os
import subprocess
import sys

RULE_BEARING = (
    "CLAUDE.md",
    "docs/invariant-register.md",
    "docs/superpowers/specs/",
)


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0
    path = (payload.get("tool_input") or {}).get("file_path") or ""
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    rel = os.path.relpath(os.path.abspath(path), root).replace(os.sep, "/")
    if not any(
        rel == p or (p.endswith("/") and rel.startswith(p)) for p in RULE_BEARING
    ):
        return 0
    try:
        out = subprocess.run(
            ["git", "status", "--porcelain", "--", "docs/RULES-GROUPED.md"],
            capture_output=True,
            text=True,
            cwd=root,
            timeout=15,
        ).stdout.strip()
    except Exception:
        return 0
    if not out:
        print(
            "Rule-bearing doc changed (%s) and the design-decision register "
            "docs/RULES-GROUPED.md is untouched. If this change adds, changes, or "
            "supersedes a rule, update the register in the same commit "
            "(/rule-intake walks the steps)." % rel
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
