// Story: register/INDEX.md's contract, made mechanical (spec I2, I13): the index is derived, never authored.
import fs from 'node:fs';
import path from 'node:path';
import { parseRuleFile } from './frontmatter.mjs';
import { SPECS_DIR, SPEC_INDEX } from './layout.mjs';

export function readRules(rulesDir) {
  return fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md')).sort()
    .map((f) => parseRuleFile(fs.readFileSync(path.join(rulesDir, f), 'utf8'), f));
}

export function generateIndex(rulesDir) {
  const entries = fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md')).sort()
    .map((f) => ({ name: f, text: fs.readFileSync(path.join(rulesDir, f), 'utf8') }));
  return generateIndexFrom(entries);
}

// entries: [{name, text}] — the rule files being indexed, already read (spec I28: lets a caller
// build the index from the STAGED tree instead of the working tree). Pure; no I/O.
export function generateIndexFrom(entries) {
  const files = entries.map((e) => parseRuleFile(e.text, e.name));
  const known = new Set(files.flatMap((f) => f.sections.map((s) => `rules/${f.name} § ${s.heading}`)));
  const rows = files.map((f) => `| rules/${f.name} | ${f.status} | ${f.rules} | ${f.sections.map((s) => s.heading).join('; ')} |`);
  const sup = [];
  for (const f of files) for (const s of f.supersedes) {
    const key = `rules/${f.name} § ${s.section}`;
    if (!known.has(key)) throw new Error(`${f.name}: supersedes names a section that does not exist: '${s.section}'`);
    sup.push({ superseded: key, by: s.by, date: s.date });
  }
  sup.sort((a, b) => a.superseded.localeCompare(b.superseded));
  const out = ['# Register index', '', 'Generated by machinery — do not edit; run /machinery:reindex.', '',
    '| File | Status | Rules | Sections |', '|---|---|---|---|', ...rows, '', '## Supersession', '',
    '| Superseded | By | Date |', '|---|---|---|', ...sup.map((s) => `| ${s.superseded} | ${s.by} | ${s.date} |`), '',
    '## Superseded by (derived)', '', '| Section | Supersedes | Date |', '|---|---|---|',
    ...[...sup].sort((a, b) => a.by.localeCompare(b.by)).map((s) => `| ${s.by} | ${s.superseded} | ${s.date} |`), ''];
  return out.join('\n');
}

export const readIndex = (file) => (fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null);

// ---------------------------------------------------------------------------- the spec index (#81)
//
// Owner ruling, 2026-09-07: specs reuse the rules layout, with SPEC_INDEX.md beside RULES_INDEX.md.
// The INDEX is symmetric; the PARSER deliberately is not. A rule file is this project's own
// artifact and its frontmatter is validated hard (an unknown status is refused, spec I16). A
// specification is somebody else's document — it may carry frontmatter this project never defined,
// or none at all — so it is parsed, not validated (rules/design-invariants.md § External input): a
// spec that would throw parseRuleFile() must still produce an index row.
//
// A spec therefore has no status and no supersession vocabulary here, and the index claims neither.
// What it states is what can be derived without a judgement: the file, and the sections in it.
export function parseSpecFile(text, name) {
  let lines = text.split(/\r?\n/);
  if (lines[0]?.trim() === '---') {
    const end = lines.indexOf('---', 1);
    if (end > 0) lines = lines.slice(end + 1); // unclosed frontmatter is data too: index the whole file
  }
  const sections = [];
  let inFence = false;
  for (const line of lines) {
    if (line.startsWith('```')) { inFence = !inFence; continue; }
    if (inFence) continue;
    const h = /^## (.+)$/.exec(line);
    if (h) sections.push(h[1].trim());
  }
  return { name, sections };
}

// entries: [{name, text}] — already read, so a caller can index the STAGED tree (spec I28).
// Pure; no I/O.
export function generateSpecIndexFrom(entries) {
  const files = entries.map((e) => parseSpecFile(e.text, e.name));
  return ['# Spec index', '', 'Generated by machinery — do not edit; run /machinery:reindex.', '',
    '| File | Sections | Headings |', '|---|---|---|',
    ...files.map((f) => `| ${SPECS_DIR}/${f.name} | ${f.sections.length} | ${f.sections.join('; ')} |`), ''].join('\n');
}

// The index lives INSIDE the directory it indexes, so it must not index itself: without this it
// would grow a row for SPEC_INDEX.md, and regenerating over its own output would never reach a
// fixed point — every run would differ from the last and the gate's comparison would never settle.
// Non-recursive, deliberately: this is the sole derivation of what the index contains, and the
// gate's staged reader is held to it.
const isSpecFile = (f) => f.endsWith('.md') && f !== SPEC_INDEX;

// A spec area that does not exist yet indexes as empty rather than throwing: that is a project with
// no specifications filed, not a misconfiguration, and never a stack trace here.
export function generateSpecIndex(specsDir) {
  const entries = fs.existsSync(specsDir)
    ? fs.readdirSync(specsDir, { withFileTypes: true })
      .filter((e) => e.isFile() && isSpecFile(e.name)).map((e) => e.name).sort()
      .map((f) => ({ name: f, text: fs.readFileSync(path.join(specsDir, f), 'utf8') }))
    : [];
  return generateSpecIndexFrom(entries);
}
