// Story: ticket #73 — the gate's composition is DERIVED from the check modules' own declarations,
// and a check cannot be unwired while a claim about it survives.
//
// On 2026-09-05 the citation-target check was unwired by owner ruling (#29) and five dependents
// survived it intact: a rules bullet still said it blocked, the installer still shipped it, a flag
// only it read was still parsed, and the ledger rows still described a mechanism nobody ran. The
// gate's list of checks was typed in one file and every claim about that list lived in four others,
// so nothing could notice the disagreement.
//
// Two invariants come out of this module:
//   I43 — gate/manifest.mjs is GENERATED from the declarations below, never typed. Spec I24 ("closed
//         check array; no config extension point") is preserved exactly: generation happens at BUILD
//         time and the runtime array stays a frozen literal. Nothing is discovered at run time.
//   I44 — every claim a check ships is walked, and a claim citing a `wired: false` check is red. The
//         unwiring is REFUSED while a dependent exists; the gate is never made to tolerate a missing
//         check (owner, 2026-09-06).
//
// A check module is DATA to this loader (rules/design-invariants.md § External input): a malformed
// declaration produces a named diagnostic, never a stack trace.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export const MANIFEST_FILE = 'manifest.mjs';

// The only two files under scripts/gate/ that are not checks: the runner (which cannot be imported
// for inspection — it has top-level side effects) and the file this module generates. Every other
// .mjs there must declare itself, so there is no way to add a file the manifest cannot see (I43.5).
// A third exemption is a visible edit to this constant, asserted by test/gate-manifest.test.mjs.
export const NOT_A_CHECK = Object.freeze(['gate.mjs', MANIFEST_FILE]);

const ID = /^[a-z][a-z0-9_]*$/;

// Diagnostics quote the offending value for a reader by hand: lib/emit.mjs is the sole JSON writer
// in scripts/ (spec I19), and gate-purity.test.mjs enforces that over the whole tree.
const q = (v) => (typeof v === 'string' ? `"${v}"` : String(v));

// Returns a diagnostic string, or null when the declaration is well formed.
function validate(file, d, mod) {
  if (d === null || typeof d !== 'object') return `${file}: \`declaration\` must be an object, got ${typeof d}`;
  if (typeof d.id !== 'string' || !ID.test(d.id)) return `${file}: \`id\` must be a lowercase_with_underscores string, got ${q(d.id)}`;
  if (typeof d.run !== 'string' || typeof mod[d.run] !== 'function') return `${file}: \`run\` must name a function this module exports, got ${q(d.run)}`;
  if (typeof d.blocking !== 'boolean') return `${file}: \`blocking\` must be a boolean, got ${q(d.blocking)}`;
  if (typeof d.wired !== 'boolean') return `${file}: \`wired\` must be a boolean, got ${q(d.wired)}`;
  if (!d.wired && (typeof d.reason !== 'string' || !d.reason.trim())) return `${file}: an unwired check must carry the \`reason\` and the ruling that unwired it`;
  if (!Array.isArray(d.claims)) return `${file}: \`claims\` must be an array (empty is a real answer; missing is not)`;
  for (const [i, c] of d.claims.entries()) {
    if (!c || typeof c.file !== 'string' || typeof c.quote !== 'string' || !c.quote.trim()) return `${file}: claims[${i}] must be {file, quote} with a non-empty quote`;
  }
  return null;
}

// Every check module under `gateDir`, sorted by id. Never throws on a bad module: problems come
// back as diagnostics so the caller decides how to print them.
export async function loadDeclarations(gateDir) {
  const problems = [];
  let files;
  try { files = fs.readdirSync(gateDir).filter((f) => f.endsWith('.mjs') && !NOT_A_CHECK.includes(f)).sort(); }
  catch (e) { return { declarations: [], problems: [`${gateDir}: cannot be read — ${e.message}`] }; }
  const declarations = [];
  for (const f of files) {
    let mod;
    try { mod = await import(pathToFileURL(path.join(gateDir, f)).href); }
    catch (e) { problems.push(`${f}: could not be imported — ${e.message}`); continue; }
    if (!('declaration' in mod)) {
      problems.push(`${f}: exports no \`declaration\` — every module under scripts/gate/ is a check and declares itself (#73, I43)`);
      continue;
    }
    const bad = validate(f, mod.declaration, mod);
    if (bad) { problems.push(bad); continue; }
    declarations.push({ ...mod.declaration, file: f });
  }
  declarations.sort((a, b) => a.id.localeCompare(b.id));
  return { declarations, problems };
}

// The generated manifest's source text. Wired checks only, in id order — there is deliberately no
// declared ordering, because no check reads another's output or assumes it ran (recon, 2026-09-06).
export function renderManifest(declarations) {
  const wired = declarations.filter((d) => d.wired);
  return [
    '// GENERATED by scripts/gate-manifest.mjs from the `declaration` each check module exports.',
    '// Do not edit: `node scripts/build-skills.mjs check` regenerates this and fails on any drift.',
    '// Spec I24 holds — this is a closed, frozen literal produced at BUILD time; nothing here is',
    '// discovered at run time and there is no configuration point (#73, I43).',
    ...wired.map((d) => `import { ${d.run} } from './${d.file}';`),
    '',
    'export const CHECKS = Object.freeze([',
    ...wired.map((d) => `  Object.freeze({ id: '${d.id}', blocking: ${d.blocking}, run: ${d.run} }),`),
    ']);',
    '',
    '// The check modules an install copies beside the gate. Derived, so an unwired module cannot be',
    '// shipped into a project that will never run it (#73).',
    `export const CHECK_FILES = Object.freeze([${wired.map((d) => `'${d.file}'`).join(', ')}]);`,
    '',
  ].join('\n');
}

// Prose wraps; a claim's quote must survive being reflowed across lines, so both sides collapse
// runs of whitespace to one space before comparison.
const flat = (s) => s.replace(/\s+/g, ' ');

// Walks every claim every check ships. `root` is the repository root the claim paths are relative
// to. Returns what it walked — the denominator — alongside the failures, so a run that found
// nothing is distinguishable from one that found nothing wrong.
export function walkClaims(declarations, root) {
  const walked = [];
  const failures = [];
  for (const d of declarations) {
    for (const c of d.claims) {
      walked.push({ check: d.id, file: c.file, quote: c.quote });
      const f = path.join(root, c.file);
      let text;
      try { text = fs.readFileSync(f, 'utf8'); }
      catch { failures.push(`${d.id}: claim site ${c.file} does not exist — amend the claim list or restore the file`); continue; }
      if (!flat(text).includes(flat(c.quote))) {
        failures.push(`${d.id}: ${c.file} no longer carries the claim ${q(c.quote)} — amend the claim list to what the file now says`);
        continue;
      }
      if (!d.wired) failures.push(`${d.id} is declared \`wired: false\`, but ${c.file} still claims it: ${q(c.quote)} — amend every claim BEFORE unwiring a check (#73, I44)`);
    }
  }
  return { walked, failures };
}
