// Story: ticket #73 — the gate's composition is DERIVED from the check modules' own declarations.
//
// On 2026-09-05 a check was unwired by owner ruling (#29) and its dependents survived it intact:
// the installer still shipped it and a flag only it read was still parsed. The gate's list of
// checks was typed in one file, so nothing could notice the disagreement.
//
// One invariant comes out of this module:
//   I43 — gate/manifest.mjs is GENERATED from the declarations below, never typed. Spec I24 ("closed
//         check array; no config extension point") is preserved exactly: generation happens at BUILD
//         time and the runtime array stays a frozen literal. Nothing is discovered at run time.
// The claims walker (I44) that once lived here was deleted by recalibration decision 49: decision 3
// removed the prose the claims cited, and a walker over zero claims checks nothing.
//
// A check module is DATA to this loader, external input that never crashes it: a malformed
// declaration produces a named diagnostic, never a stack trace.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export const MANIFEST_FILE = 'manifest.mjs';

// The only two files under scripts/gate/ that are not checks: the runner (which cannot be imported
// for inspection — it has top-level side effects) and the file this module generates. Every other
// .mjs there must declare itself, so there is no way to add a file the manifest cannot see (I43.5).
// A third exemption is a visible edit to this constant, asserted by test/gate-manifest.test.mjs.
export const NOT_A_CHECK = Object.freeze(['gate.mjs', MANIFEST_FILE]);

const ID = /^[a-z][a-z0-9_]*$/;

// Diagnostics quote the offending value for a reader by hand: lib/emit.mjs is the sole JSON writer
// in scripts/ (spec I19), and gate-purity.test.mjs enforces that over the whole tree.
const q = (v) => (typeof v === 'string' ? `"${v}"` : String(v));

// Returns a diagnostic string, or null when the declaration is well formed.
function validate(file, d, mod) {
  if (d === null || typeof d !== 'object') return `${file}: \`declaration\` must be an object, got ${typeof d}`;
  if (typeof d.id !== 'string' || !ID.test(d.id)) return `${file}: \`id\` must be a lowercase_with_underscores string, got ${q(d.id)}`;
  if (typeof d.run !== 'string' || typeof mod[d.run] !== 'function') return `${file}: \`run\` must name a function this module exports, got ${q(d.run)}`;
  if (typeof d.blocking !== 'boolean') return `${file}: \`blocking\` must be a boolean, got ${q(d.blocking)}`;
  if (typeof d.wired !== 'boolean') return `${file}: \`wired\` must be a boolean, got ${q(d.wired)}`;
  if (!d.wired && (typeof d.reason !== 'string' || !d.reason.trim())) return `${file}: an unwired check must carry the \`reason\` and the ruling that unwired it`;
  return null;
}

// Every check module under `gateDir`, sorted by id. Never throws on a bad module: problems come
// back as diagnostics so the caller decides how to print them.
export async function loadDeclarations(gateDir) {
  const problems = [];
  let files;
  try { files = fs.readdirSync(gateDir).filter((f) => f.endsWith('.mjs') && !NOT_A_CHECK.includes(f)).sort(); }
  catch (e) { return { declarations: [], problems: [`${gateDir}: cannot be read — ${e.message}`] }; }
  const declarations = [];
  for (const f of files) {
    let mod;
    try { mod = await import(pathToFileURL(path.join(gateDir, f)).href); }
    catch (e) { problems.push(`${f}: could not be imported — ${e.message}`); continue; }
    if (!('declaration' in mod)) {
      problems.push(`${f}: exports no \`declaration\` — every module under scripts/gate/ is a check and declares itself (#73, I43)`);
      continue;
    }
    const bad = validate(f, mod.declaration, mod);
    if (bad) { problems.push(bad); continue; }
    declarations.push({ ...mod.declaration, file: f });
  }
  declarations.sort((a, b) => a.id.localeCompare(b.id));
  return { declarations, problems };
}

// The generated manifest's source text. Wired checks only, in id order — there is deliberately no
// declared ordering, because no check reads another's output or assumes it ran (recon, 2026-09-06).
export function renderManifest(declarations) {
  const wired = declarations.filter((d) => d.wired);
  return [
    '// GENERATED by scripts/gate-manifest.mjs from the `declaration` each check module exports.',
    '// Do not edit: `node scripts/build-skills.mjs check` regenerates this and fails on any drift.',
    '// Spec I24 holds — this is a closed, frozen literal produced at BUILD time; nothing here is',
    '// discovered at run time and there is no configuration point (#73, I43).',
    ...wired.map((d) => `import { ${d.run} } from './${d.file}';`),
    '',
    'export const CHECKS = Object.freeze([',
    ...wired.map((d) => `  Object.freeze({ id: '${d.id}', blocking: ${d.blocking}, run: ${d.run} }),`),
    ']);',
    '',
    '// The check modules an install copies beside the gate. Derived, so an unwired module cannot be',
    '// shipped into a project that will never run it (#73).',
    `export const CHECK_FILES = Object.freeze([${wired.map((d) => `'${d.file}'`).join(', ')}]);`,
    '',
  ].join('\n');
}
